apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: {{ .Values.namespace }}
spec:
  acme:
    email: mail.akashkamble@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - http01:
        ingress:
          # ingressClassName: alb
          # serviceType: NodePort
          name: django-ingress