apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: staticvolume-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2  

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediavolume-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2 