apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SECRET_KEY: {{ required ".Values.secrets.SECRET_KEY is required" .Values.secrets.SECRET_KEY | quote }}
  POSTGRES_PASSWORD: {{ required ".Values.secrets.POSTGRES_PASSWORD is required" .Values.secrets.POSTGRES_PASSWORD | quote }}
  DJANGO_SUPERUSER_PASSWORD: {{ required ".Values.secrets.DJANGO_SUPERUSER_PASSWORD is required" .Values.secrets.DJANGO_SUPERUSER_PASSWORD | quote }}
  CSRF_TRUSTED_ORIGINS: {{ required ".Values.secrets.CSRF_TRUSTED_ORIGINS is required" .Values.secrets.CSRF_TRUSTED_ORIGINS | quote }}